name: basketball
favicon: null
layout_spectrum: 0.5732416564133018
typography_spectrum: 0.32075759558938444
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors: []
  brandStrength: 0
  lightness: 0.5
  saturation: 0.5
  rhythmicContrast: 0.8810903360135853
purpose:
  - name: follow
    item: null
    url: null
